# Import packages

In [32]:
install.packages("readr")
install.packages("readxl")
install.packages("dpylr")
install.packages ("tidyverse")
install.packages ("tidyr")
library(tidyr)
library(tidyverse)
library (dpylr)
library (readr)
library (readxl)
install.packages("gmodels")
library("gmodels")

The downloaded binary packages are in
	/var/folders/b6/tn8p_f9d1ls_4qs2b7h32md00000gn/T//RtmpvgPiGT/downloaded_packages

The downloaded binary packages are in
	/var/folders/b6/tn8p_f9d1ls_4qs2b7h32md00000gn/T//RtmpvgPiGT/downloaded_packages

Warning message:
“package ‘dpylr’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages”

The downloaded binary packages are in
	/var/folders/b6/tn8p_f9d1ls_4qs2b7h32md00000gn/T//RtmpvgPiGT/downloaded_packages

The downloaded binary packages are in
	/var/folders/b6/tn8p_f9d1ls_4qs2b7h32md00000gn/T//RtmpvgPiGT/downloaded_packages

ERROR: Error in value[[3L]](cond): Package ‘tidyr’ version 1.2.0 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘tidyr’ is imported by ‘broom’ so cannot be unloaded

# Import data

In [33]:
loans <- read_csv('/Users/christinasimbenga/Desktop/loans.csv')

New names:
• `` -> `...1`
Rows: 21957 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): term, loan_status, Date, home_ownership
dbl (1): ...1

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [34]:
loans

      ...1  term      loan_status Date      home_ownership
1      1    36 months Fully Paid  12/1/2011 RENT
2      2    60 months Charged Off 12/1/2011 RENT
3      3    36 months Fully Paid  12/1/2011 RENT
4      4    36 months Fully Paid  12/1/2011 RENT
5      5    60 months Current     12/1/2011 RENT
6      6    36 months Fully Paid  12/1/2011 RENT
7      7    60 months Fully Paid  12/1/2011 RENT
8      8    36 months Fully Paid  12/1/2011 RENT
9      9    60 months Charged Off 12/1/2011 OWN
10    10    60 months Charged Off 12/1/2011 RENT
11    11    60 months Fully Paid  12/1/2011 OWN
12    12    36 months Fully Paid  12/1/2011 OWN
13    13    36 months Charged Off 12/1/2011 RENT
14    14    36 months Fully Paid  12/1/2011 RENT
15    15    36 months Charged Off 12/1/2011 RENT
16    16    36 months Fully Paid  12/1/2011 RENT
17    17    36 months Fully Paid  12/1/2011 RENT
18    18    36 months Fully Paid  12/1/2011 RENT
19    19    60 months Fully Paid  12/1/2011 RENT
20    20    36 months Charged Off 12/1/2011 RENT
21    21    36 months Fully Paid  12/1/2011 OWN
22    22    36 months Fully Paid  12/1/2011 RENT
23    23    36 months Charged Off 12/1/2011 RENT
24    24    36 months Charged Off 12/1/2011 RENT
25    25    60 months Charged Off 12/1/2011 RENT
26    26    36 months Fully Paid  12/1/2011 RENT
27    27    60 months Current     12/1/2011 RENT
28    28    36 months Fully Paid  12/1/2011 RENT
29    29    36 months Fully Paid  12/1/2011 RENT
30    30    36 months Fully Paid  12/1/2011 RENT
⋮     ⋮     ⋮         ⋮           ⋮         ⋮
21928 21928 36 months Fully Paid  8/1/2007  OWN
21929 21929 36 months Fully Paid  8/1/2007  OWN
21930 21930 36 months Fully Paid  8/1/2007  RENT
21931 21931 36 months Fully Paid  8/1/2007  RENT
21932 21932 36 months Fully Paid  8/1/2007  RENT
21933 21933 36 months Fully Paid  8/1/2007  RENT
21934 21934 36 months Fully Paid  8/1/2007  RENT
21935 21935 36 months Fully Paid  8/1/2007  RENT
21936 21936 36 months Fully Paid  8/1/2007  RENT
21937 21937 36 months Fully Paid  8/1/2007  RENT
21938 21938 36 months Fully Paid  7/1/2007  RENT
21939 21939 36 months Fully Paid  7/1/2007  RENT
21940 21940 36 months Fully Paid  8/1/2007  RENT
21941 21941 36 months Fully Paid  8/1/2007  OWN
21942 21942 36 months Fully Paid  8/1/2007  RENT
21943 21943 36 months Fully Paid  8/1/2007  OWN
21944 21944 36 months Fully Paid  7/1/2007  RENT
21945 21945 36 months Fully Paid  7/1/2007  RENT
21946 21946 36 months Fully Paid  7/1/2007  RENT
21947 21947 36 months Fully Paid  7/1/2007  RENT
21948 21948 36 months Fully Paid  7/1/2007  RENT
21949 21949 36 months Fully Paid  7/1/2007  RENT
21950 21950 36 months Fully Paid  7/1/2007  RENT
21951 21951 36 months Fully Paid  7/1/2007  RENT
21952 21952 36 months Fully Paid  7/1/2007  RENT
21953 21953 36 months Fully Paid  7/1/2007  OWN
21954 21954 36 months Fully Paid  7/1/2007  OWN
21955 21955 36 months Fully Paid  7/1/2007  OWN
21956 21956 36 months Fully Paid  7/1/2007  RENT
21957 21957 36 months Fully Paid  6/1/2007  OWN

# Data Wrangling

In [35]:
str(loans)

spec_tbl_df [21,957 × 5] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ ...1          : num [1:21957] 1 2 3 4 5 6 7 8 9 10 ...
 $ term          : chr [1:21957] "36 months" "60 months" "36 months" "36 months" ...
 $ loan_status   : chr [1:21957] "Fully Paid" "Charged Off" "Fully Paid" "Fully Paid" ...
 $ Date          : chr [1:21957] "12/1/2011" "12/1/2011" "12/1/2011" "12/1/2011" ...
 $ home_ownership: chr [1:21957] "RENT" "RENT" "RENT" "RENT" ...
 - attr(*, "spec")=
  .. cols(
  ..   ...1 = col_double(),
  ..   term = col_character(),
  ..   loan_status = col_character(),
  ..   Date = col_character(),
  ..   home_ownership = col_character()
  .. )
 - attr(*, "problems")=<externalptr>

In [36]:
loans %>% group_by(loan_status)%>%summarize (count-n())

ERROR: Error in loans %>% group_by(loan_status) %>% summarize(count - n()): could not find function "%>%"

# Part I

Please answer the following question.

Does the term of the loan influence loan status? If so, how?

## Testing Assumptions and Running the Analysis

In [37]:
colnames(loans)

[1] "...1"           "term"           "loan_status"    "Date"
[5] "home_ownership"

In [38]:
CrossTable(loans$term, loans$loan_status, fisher=TRUE, chisq = TRUE, expected = TRUE, sresid=TRUE, format="SPSS")

   Cell Contents
|-------------------------|
|                   Count |
|         Expected Values |
| Chi-square contribution |
|             Row Percent |
|          Column Percent |
|           Total Percent |
|            Std Residual |
|-------------------------|

Total Observations in Table:  21957

             | loans$loan_status
  loans$term | Charged Off  |     Current  |  Fully Paid  |   Row Total |
-------------|-------------|-------------|-------------|-------------|
   36 months |       2029  |          0  |      14964  |      16993  |
             |   2540.011  |    388.509  |  14064.480  |             |
             |    102.808  |    388.509  |     57.530  |             |
             |     11.940% |      0.000% |     88.060% |     77.392% |
             |     61.822% |      0.000% |     82.342% |             |
             |      9.241% |      0.000% |     68.151% |             |
             |    -10.139  |    -19.711  |      7.585  |             |
-------------|-------------|-------------|-------------|-------------|
   60 months |       1253  |        502  |       3209  |       4964  |
             |    741.989  |    113.491  |   4108.520  |             |
             |    351.936  |   1329.961  |    196.941  |             |
             |     25.242% |     10.113% |     64.645% |     22.608% |
             |     38.178% |    100.000% |     17.658% |             |
             |      5.707% |      2.286% |     14.615% |             |
             |     18.760  |     36.469  |    -14.034  |             |
-------------|-------------|-------------|-------------|-------------|
Column Total |       3282  |        502  |      18173  |      21957  |
             |     14.947% |      2.286% |     82.766% |             |
-------------|-------------|-------------|-------------|-------------|


Statistics for All Table Factors


Pearson's Chi-squared test
------------------------------------------------------------
Chi^2 =  2427.685     d.f. =  2     p =  0

ERROR: Error in fisher.test(t, alternative = "two.sided"): FEXACT error 6 (f5xact).  LDKEY=484 is too small for this problem: kval=84285355.
Try increasing the size of the workspace.

p value is 0 less than .05, making this analysis significant. Meaning there is a difference between the term and loan status. The expected values for the cells is more than 5 meaning we have meet the assumptions of chisquare. The term can show how long you had the loan and the loan status depending on how long its has been shows if it is paid off and the amount of time it took to pay it off.

# Part II

Please answer the following question.

How has the ability to own a home changed after 2009?

### Reformatting to a Date

In [39]:
loans$DateR <- as.Date(paste(loans$Date), "%m/%d/%Y")

In [40]:
loans

      ...1  term      loan_status Date      home_ownership DateR
1      1    36 months Fully Paid  12/1/2011 RENT           2011-12-01
2      2    60 months Charged Off 12/1/2011 RENT           2011-12-01
3      3    36 months Fully Paid  12/1/2011 RENT           2011-12-01
4      4    36 months Fully Paid  12/1/2011 RENT           2011-12-01
5      5    60 months Current     12/1/2011 RENT           2011-12-01
6      6    36 months Fully Paid  12/1/2011 RENT           2011-12-01
7      7    60 months Fully Paid  12/1/2011 RENT           2011-12-01
8      8    36 months Fully Paid  12/1/2011 RENT           2011-12-01
9      9    60 months Charged Off 12/1/2011 OWN            2011-12-01
10    10    60 months Charged Off 12/1/2011 RENT           2011-12-01
11    11    60 months Fully Paid  12/1/2011 OWN            2011-12-01
12    12    36 months Fully Paid  12/1/2011 OWN            2011-12-01
13    13    36 months Charged Off 12/1/2011 RENT           2011-12-01
14    14    36 months Fully Paid  12/1/2011 RENT           2011-12-01
15    15    36 months Charged Off 12/1/2011 RENT           2011-12-01
16    16    36 months Fully Paid  12/1/2011 RENT           2011-12-01
17    17    36 months Fully Paid  12/1/2011 RENT           2011-12-01
18    18    36 months Fully Paid  12/1/2011 RENT           2011-12-01
19    19    60 months Fully Paid  12/1/2011 RENT           2011-12-01
20    20    36 months Charged Off 12/1/2011 RENT           2011-12-01
21    21    36 months Fully Paid  12/1/2011 OWN            2011-12-01
22    22    36 months Fully Paid  12/1/2011 RENT           2011-12-01
23    23    36 months Charged Off 12/1/2011 RENT           2011-12-01
24    24    36 months Charged Off 12/1/2011 RENT           2011-12-01
25    25    60 months Charged Off 12/1/2011 RENT           2011-12-01
26    26    36 months Fully Paid  12/1/2011 RENT           2011-12-01
27    27    60 months Current     12/1/2011 RENT           2011-12-01
28    28    36 months Fully Paid  12/1/2011 RENT           2011-12-01
29    29    36 months Fully Paid  12/1/2011 RENT           2011-12-01
30    30    36 months Fully Paid  12/1/2011 RENT           2011-12-01
⋮     ⋮     ⋮         ⋮           ⋮         ⋮              ⋮
21928 21928 36 months Fully Paid  8/1/2007  OWN            2007-08-01
21929 21929 36 months Fully Paid  8/1/2007  OWN            2007-08-01
21930 21930 36 months Fully Paid  8/1/2007  RENT           2007-08-01
21931 21931 36 months Fully Paid  8/1/2007  RENT           2007-08-01
21932 21932 36 months Fully Paid  8/1/2007  RENT           2007-08-01
21933 21933 36 months Fully Paid  8/1/2007  RENT           2007-08-01
21934 21934 36 months Fully Paid  8/1/2007  RENT           2007-08-01
21935 21935 36 months Fully Paid  8/1/2007  RENT           2007-08-01
21936 21936 36 months Fully Paid  8/1/2007  RENT           2007-08-01
21937 21937 36 months Fully Paid  8/1/2007  RENT           2007-08-01
21938 21938 36 months Fully Paid  7/1/2007  RENT           2007-07-01
21939 21939 36 months Fully Paid  7/1/2007  RENT           2007-07-01
21940 21940 36 months Fully Paid  8/1/2007  RENT           2007-08-01
21941 21941 36 months Fully Paid  8/1/2007  OWN            2007-08-01
21942 21942 36 months Fully Paid  8/1/2007  RENT           2007-08-01
21943 21943 36 months Fully Paid  8/1/2007  OWN            2007-08-01
21944 21944 36 months Fully Paid  7/1/2007  RENT           2007-07-01
21945 21945 36 months Fully Paid  7/1/2007  RENT           2007-07-01
21946 21946 36 months Fully Paid  7/1/2007  RENT           2007-07-01
21947 21947 36 months Fully Paid  7/1/2007  RENT           2007-07-01
21948 21948 36 months Fully Paid  7/1/2007  RENT           2007-07-01
21949 21949 36 months Fully Paid  7/1/2007  RENT           2007-07-01
21950 21950 36 months Fully Paid  7/1/2007  RENT           2007-07-01
21951 21951 36 months Fully Paid  7/1/2007  RENT           2007-07-01
21952 21952 36 months Fully Paid  7/1/2007  RENT           2007-07-01
21953 21953 36 months Fully Paid  7/1/2007  OWN            2007-07-01
21954 21954 36 months Fully Paid  7/1/2007  OWN            2007-07-01
21955 21955 36 months Fully Paid  7/1/2007  OWN            2007-07-01
21956 21956 36 months Fully Paid  7/1/2007  RENT           2007-07-01
21957 21957 36 months Fully Paid  6/1/2007  OWN            2007-06-01

In [42]:
loans$DateR <- NA
loans$DateR[loans$Date == 2007] <- 1
loans$DateR[loans$Date > 2007] <- 0

In [44]:
loans$ownership <- NA
loans$ownership[loans$home_ownership == "OWN"] <- 1
loans$ownership[loans$home_ownership != "OWN"] <- 0

In [46]:
loans1 <- na.omit("loans")

## Test Assumptions and Run Analyses

In [56]:
CrossTable(loans$Date, loans$ownership, fisher=TRUE, chisq = TRUE, mcnemar = TRUE, expected = TRUE, sresid=TRUE, format="SPSS")

Warning message in chisq.test(t, correct = FALSE, ...):
“Chi-squared approximation may be incorrect”

   Cell Contents
|-------------------------|
|                   Count |
|         Expected Values |
| Chi-square contribution |
|             Row Percent |
|          Column Percent |
|           Total Percent |
|            Std Residual |
|-------------------------|

Total Observations in Table:  21957

             | loans$ownership
  loans$Date |        0  |        1  | Row Total |
-------------|-----------|-----------|-----------|
    1/1/2008 |       92  |       10  |      102  |
             |   87.794  |   14.206  |           |
             |    0.201  |    1.245  |           |
             |   90.196% |    9.804% |    0.465% |
             |    0.487% |    0.327% |           |
             |    0.419% |    0.046% |           |
             |    0.449  |   -1.116  |           |
-------------|-----------|-----------|-----------|
    1/1/2009 |      125  |       11  |      136  |
             |  117.059  |   18.941  |           |
             |    0.539  |    3.329  |           |
             |   91.912% |    8.088% |    0.619% |
             |    0.661% |    0.360% |           |
             |    0.569% |    0.050% |           |
             |    0.734  |   -1.825  |           |
-------------|-----------|-----------|-----------|
    1/1/2010 |      290  |       80  |      370  |
             |  318.469  |   51.531  |           |
             |    2.545  |   15.728  |           |
             |   78.378% |   21.622% |    1.685% |
             |    1.534% |    2.616% |           |
             |    1.321% |    0.364% |           |
             |   -1.595  |    3.966  |           |
-------------|-----------|-----------|-----------|
    1/1/2011 |      662  |      100  |      762  |
             |  655.875  |  106.125  |           |
             |    0.057  |    0.354  |           |
             |   86.877% |   13.123% |    3.470% |
             |    3.503% |    3.270% |           |
             |    3.015% |    0.455% |           |
             |    0.239  |   -0.595  |           |
-------------|-----------|-----------|-----------|
   10/1/2007 |       24  |        4  |       28  |
             |   24.100  |    3.900  |           |
             |    0.000  |    0.003  |           |
             |   85.714% |   14.286% |    0.128% |
             |    0.127% |    0.131% |           |
             |    0.109% |    0.018% |           |
             |   -0.020  |    0.051  |           |
-------------|-----------|-----------|-----------|
   10/1/2008 |       46  |        4  |       50  |
             |   43.036  |    6.964  |           |
             |    0.204  |    1.261  |           |
             |   92.000% |    8.000% |    0.228% |
             |    0.243% |    0.131% |           |
             |    0.210% |    0.018% |           |
             |    0.452  |   -1.123  |           |
-------------|-----------|-----------|-----------|
   10/1/2009 |      286  |       51  |      337  |
             |  290.065  |   46.935  |           |
             |    0.057  |    0.352  |           |
             |   84.866% |   15.134% |    1.535% |
             |    1.513% |    1.668% |           |
             |    1.303% |    0.232% |           |
             |   -0.239  |    0.593  |           |
-------------|-----------|-----------|-----------|
   10/1/2010 |      529  |       97  |      626  |
             |  538.816  |   87.184  |           |
             |    0.179  |    1.105  |           |
             |   84.505% |   15.495% |    2.851% |
             |    2.799% |    3.172% |           |
             |    2.409% |    0.442% |           |
             |   -0.423  |    1.051  |           |
-------------|-----------|-----------|-----------|
   10/1/2011 |      864  |      159  |     1023  |
             |  880.525  |  142.475  |           |
             |    0.310  |    1.917  |           |
             |   84.457% |   15.543% |    4.659% |
             |    4.572% |    5.199% |           |
             |    3.935% |    0.724% |           |
             |   -0.557  |    1.384  |           |
-------------|-----------|-----------|-----------|
   11/1/2007 |       21  |        0  |       21  |
             |   18.075  |    2.925  |           |
             |    0.473  |    2.925  |           |
             |  100.000% |    0.000% |    0.096% |
             |    0.111% |    0.000% |           |
             |    0.096% |    0.000% |           |
             |    0.688  |   -1.710  |           |
-------------|-----------|-----------|-----------|
   11/1/2008 |       92  |       10  |      102  |
             |   87.794  |   14.206  |           |
             |    0.201  |    1.245  |           |
             |   90.196% |    9.804% |    0.465% |
             |    0.487% |    0.327% |           |
             |    0.419% |    0.046% |           |
             |    0.449  |   -1.116  |           |
-------------|-----------|-----------|-----------|
   11/1/2009 |      320  |       78  |      398  |
             |  342.570  |   55.430  |           |
             |    1.487  |    9.190  |           |
             |   80.402% |   19.598% |    1.813% |
             |    1.693% |    2.551% |           |
             |    1.457% |    0.355% |           |
             |   -1.219  |    3.031  |           |
-------------|-----------|-----------|-----------|
   11/1/2010 |      502  |       82  |      584  |
             |  502.665  |   81.335  |           |
             |    0.001  |    0.005  |           |
             |   85.959% |   14.041% |    2.660% |
             |    2.656% |    2.681% |           |
             |    2.286% |    0.373% |           |
             |   -0.030  |    0.074  |           |
-------------|-----------|-----------|-----------|
   11/1/2011 |     1059  |      162  |     1221  |
             | 1050.949  |  170.051  |           |
             |    0.062  |    0.381  |           |
             |   86.732% |   13.268% |    5.561% |
             |    5.603% |    5.298% |           |
             |    4.823% |    0.738% |           |
             |    0.248  |   -0.617  |           |
-------------|-----------|-----------|-----------|
   12/1/2007 |       54  |        6  |       60  |
             |   51.644  |    8.356  |           |
             |    0.108  |    0.664  |           |
             |   90.000% |   10.000% |    0.273% |
             |    0.286% |    0.196% |           |
             |    0.246% |    0.027% |           |
             |    0.328  |   -0.815  |           |
-------------|-----------|-----------|-----------|
   12/1/2008 |      103  |       16  |      119  |
             |  102.427  |   16.573  |           |
             |    0.003  |    0.020  |           |
             |   86.555% |   13.445% |    0.542% |
             |    0.545% |    0.523% |           |
             |    0.469% |    0.073% |           |
             |    0.057  |   -0.141  |           |
-------------|-----------|-----------|-----------|
   12/1/2009 |      283  |      109  |      392  |
             |  337.405  |   54.595  |           |
             |    8.773  |   54.217  |           |
             |   72.194% |   27.806% |    1.785% |
             |    1.497% |    3.564% |           |
             |    1.289% |    0.496% |           |
             |   -2.962  |    7.363  |           |
-------------|-----------|-----------|-----------|
   12/1/2010 |      590  |       96  |      686  |
             |  590.459  |   95.541  |           |
             |    0.000  |    0.002  |           |
             |   86.006% |   13.994% |    3.124% |
             |    3.122% |    3.139% |           |
             |    2.687% |    0.437% |           |
             |   -0.019  |    0.047  |           |
-------------|-----------|-----------|-----------|
   12/1/2011 |     1229  |      179  |     1408  |
             | 1211.905  |  196.095  |           |
             |    0.241  |    1.490  |           |
             |   87.287% |   12.713% |    6.413% |
             |    6.503% |    5.853% |           |
             |    5.597% |    0.815% |           |
             |    0.491  |   -1.221  |           |
-------------|-----------|-----------|-----------|
    2/1/2008 |      101  |       20  |      121  |
             |  104.148  |   16.852  |           |
             |    0.095  |    0.588  |           |
             |   83.471% |   16.529% |    0.551% |
             |    0.534% |    0.654% |           |
             |    0.460% |    0.091% |           |
             |   -0.308  |    0.767  |           |
-------------|-----------|-----------|-----------|
    2/1/2009 |      152  |       13  |      165  |
             |  142.020  |   22.980  |           |
             |    0.701  |    4.334  |           |
             |   92.121% |    7.879% |    0.751% |
             |    0.804% |    0.425% |           |
             |    0.692% |    0.059% |           |
             |    0.837  |   -2.082  |           |
-------------|-----------|-----------|-----------|
    2/1/2010 |      315  |       68  |      383  |
             |  329.659  |   53.341  |           |
             |    0.652  |    4.028  |           |
             |   82.245% |   17.755% |    1.744% |
             |    1.667% |    2.224% |           |
             |    1.435% |    0.310% |           |
             |   -0.807  |    2.007  |           |
-------------|-----------|-----------|-----------|
    2/1/2011 |      625  |       86  |      711  |
             |  611.977  |   99.023  |           |
             |    0.277  |    1.713  |           |
             |   87.904% |   12.096% |    3.238% |
             |    3.307% |    2.812% |           |
             |    2.846% |    0.392% |           |
             |    0.526  |   -1.309  |           |
-------------|-----------|-----------|-----------|
    3/1/2008 |      135  |       14  |      149  |
             |  128.248  |   20.752  |           |
             |    0.355  |    2.197  |           |
             |   90.604% |    9.396% |    0.679% |
             |    0.714% |    0.458% |           |
             |    0.615% |    0.064% |           |
             |    0.596  |   -1.482  |           |
-------------|-----------|-----------|-----------|
    3/1/2009 |      150  |       22  |      172  |
             |  148.045  |   23.955  |           |
             |    0.026  |    0.160  |           |
             |   87.209% |   12.791% |    0.783% |
             |    0.794% |    0.719% |           |
             |    0.683% |    0.100% |           |
             |    0.161  |   -0.399  |           |
-------------|-----------|-----------|-----------|
    3/1/2010 |      358  |       52  |      410  |
             |  352.898  |   57.102  |           |
             |    0.074  |    0.456  |           |
             |   87.317% |   12.683% |    1.867% |
             |    1.894% |    1.700% |           |
             |    1.630% |    0.237% |           |
             |    0.272  |   -0.675  |           |
-------------|-----------|-----------|-----------|
    3/1/2011 |      673  |      115  |      788  |
             |  678.253  |  109.747  |           |
             |    0.041  |    0.251  |           |
             |   85.406% |   14.594% |    3.589% |
             |    3.561% |    3.761% |           |
             |    3.065% |    0.524% |           |
             |   -0.202  |    0.501  |           |
-------------|-----------|-----------|-----------|
    4/1/2008 |       67  |       20  |       87  |
             |   74.883  |   12.117  |           |
             |    0.830  |    5.129  |           |
             |   77.011% |   22.989% |    0.396% |
             |    0.355% |    0.654% |           |
             |    0.305% |    0.091% |           |
             |   -0.911  |    2.265  |           |
-------------|-----------|-----------|-----------|
    4/1/2009 |      157  |       18  |      175  |
             |  150.627  |   24.373  |           |
             |    0.270  |    1.666  |           |
             |   89.714% |   10.286% |    0.797% |
             |    0.831% |    0.589% |           |
             |    0.715% |    0.082% |           |
             |    0.519  |   -1.291  |           |
-------------|-----------|-----------|-----------|
    4/1/2010 |      450  |       42  |      492  |
             |  423.478  |   68.522  |           |
             |    1.661  |   10.266  |           |
             |   91.463% |    8.537% |    2.241% |
             |    2.381% |    1.373% |           |
             |    2.049% |    0.191% |           |
             |    1.289  |   -3.204  |           |
-------------|-----------|-----------|-----------|
    4/1/2011 |      750  |      107  |      857  |
             |  737.644  |  119.356  |           |
             |    0.207  |    1.279  |           |
             |   87.515% |   12.485% |    3.903% |
             |    3.968% |    3.499% |           |
             |    3.416% |    0.487% |           |
             |    0.455  |   -1.131  |           |
-------------|-----------|-----------|-----------|
    5/1/2008 |       41  |        1  |       42  |
             |   36.151  |    5.849  |           |
             |    0.651  |    4.020  |           |
             |   97.619% |    2.381% |    0.191% |
             |    0.217% |    0.033% |           |
             |    0.187% |    0.005% |           |
             |    0.807  |   -2.005  |           |
-------------|-----------|-----------|-----------|
    5/1/2009 |      158  |       21  |      179  |
             |  154.070  |   24.930  |           |
             |    0.100  |    0.619  |           |
             |   88.268% |   11.732% |    0.815% |
             |    0.836% |    0.687% |           |
             |    0.720% |    0.096% |           |
             |    0.317  |   -0.787  |           |
-------------|-----------|-----------|-----------|
    5/1/2010 |      461  |       60  |      521  |
             |  448.439  |   72.561  |           |
             |    0.352  |    2.174  |           |
             |   88.484% |   11.516% |    2.373% |
             |    2.439% |    1.962% |           |
             |    2.100% |    0.273% |           |
             |    0.593  |   -1.475  |           |
-------------|-----------|-----------|-----------|
    5/1/2011 |      717  |      142  |      859  |
             |  739.365  |  119.635  |           |
             |    0.677  |    4.181  |           |
             |   83.469% |   16.531% |    3.912% |
             |    3.794% |    4.644% |           |
             |    3.265% |    0.647% |           |
             |   -0.823  |    2.045  |           |
-------------|-----------|-----------|-----------|
    6/1/2007 |        0  |        1  |        1  |
             |    0.861  |    0.139  |           |
             |    0.861  |    5.319  |           |
             |    0.000% |  100.000% |    0.005% |
             |    0.000% |    0.033% |           |
             |    0.000% |    0.005% |           |
             |   -0.928  |    2.306  |           |
-------------|-----------|-----------|-----------|
    6/1/2008 |       37  |        4  |       41  |
             |   35.290  |    5.710  |           |
             |    0.083  |    0.512  |           |
             |   90.244% |    9.756% |    0.187% |
             |    0.196% |    0.131% |           |
             |    0.169% |    0.018% |           |
             |    0.288  |   -0.716  |           |
-------------|-----------|-----------|-----------|
    6/1/2009 |      183  |       28  |      211  |
             |  181.614  |   29.386  |           |
             |    0.011  |    0.065  |           |
             |   86.730% |   13.270% |    0.961% |
             |    0.968% |    0.916% |           |
             |    0.833% |    0.128% |           |
             |    0.103  |   -0.256  |           |
-------------|-----------|-----------|-----------|
    6/1/2010 |      488  |       70  |      558  |
             |  480.286  |   77.714  |           |
             |    0.124  |    0.766  |           |
             |   87.455% |   12.545% |    2.541% |
             |    2.582% |    2.289% |           |
             |    2.223% |    0.319% |           |
             |    0.352  |   -0.875  |           |
-------------|-----------|-----------|-----------|
    6/1/2011 |      809  |      138  |      947  |
             |  815.109  |  131.891  |           |
             |    0.046  |    0.283  |           |
             |   85.428% |   14.572% |    4.313% |
             |    4.281% |    4.513% |           |
             |    3.684% |    0.629% |           |
             |   -0.214  |    0.532  |           |
-------------|-----------|-----------|-----------|
    7/1/2007 |       12  |        3  |       15  |
             |   12.911  |    2.089  |           |
             |    0.064  |    0.397  |           |
             |   80.000% |   20.000% |    0.068% |
             |    0.063% |    0.098% |           |
             |    0.055% |    0.014% |           |
             |   -0.254  |    0.630  |           |
-------------|-----------|-----------|-----------|
    7/1/2008 |       50  |        5  |       55  |
             |   47.340  |    7.660  |           |
             |    0.149  |    0.924  |           |
             |   90.909% |    9.091% |    0.250% |
             |    0.265% |    0.164% |           |
             |    0.228% |    0.023% |           |
             |    0.387  |   -0.961  |           |
-------------|-----------|-----------|-----------|
    7/1/2009 |      198  |       22  |      220  |
             |  189.360  |   30.640  |           |
             |    0.394  |    2.436  |           |
             |   90.000% |   10.000% |    1.002% |
             |    1.048% |    0.719% |           |
             |    0.902% |    0.100% |           |
             |    0.628  |   -1.561  |           |
-------------|-----------|-----------|-----------|
    7/1/2010 |      539  |       83  |      622  |
             |  535.373  |   86.627  |           |
             |    0.025  |    0.152  |           |
             |   86.656% |   13.344% |    2.833% |
             |    2.852% |    2.714% |           |
             |    2.455% |    0.378% |           |
             |    0.157  |   -0.390  |           |
-------------|-----------|-----------|-----------|
    7/1/2011 |      817  |      139  |      956  |
             |  822.856  |  133.144  |           |
             |    0.042  |    0.258  |           |
             |   85.460% |   14.540% |    4.354% |
             |    4.323% |    4.545% |           |
             |    3.721% |    0.633% |           |
             |   -0.204  |    0.507  |           |
-------------|-----------|-----------|-----------|
    8/1/2007 |       12  |        6  |       18  |
             |   15.493  |    2.507  |           |
             |    0.788  |    4.867  |           |
             |   66.667% |   33.333% |    0.082% |
             |    0.063% |    0.196% |           |
             |    0.055% |    0.027% |           |
             |   -0.887  |    2.206  |           |
-------------|-----------|-----------|-----------|
    8/1/2008 |       47  |        3  |       50  |
             |   43.036  |    6.964  |           |
             |    0.365  |    2.256  |           |
             |   94.000% |    6.000% |    0.228% |
             |    0.249% |    0.098% |           |
             |    0.214% |    0.014% |           |
             |    0.604  |   -1.502  |           |
-------------|-----------|-----------|-----------|
    8/1/2009 |      207  |       25  |      232  |
             |  199.689  |   32.311  |           |
             |    0.268  |    1.654  |           |
             |   89.224% |   10.776% |    1.057% |
             |    1.095% |    0.818% |           |
             |    0.943% |    0.114% |           |
             |    0.517  |   -1.286  |           |

ERROR: Error in mcnemar.test(t, correct = FALSE): 'x' must be square with at least two rows and columns

Not sure why it was not letting me use the DateR column. It gives an error.

I don't think I ran this correctly. The p value is very small meaning there is a change when it comes to owning a home now and what it was back then in 2009 if I ran the analysis correctly. The execpted value assumpition is met for the most part. It would make sense if owning a home has changed since 2009 as housing prices may of gone up or down and maybe its easier now to get a loan or it was easier back then.

# PART 3

Part III
Please answer the following question.

The news just ran a story that only 15% of homes are fully paid for in America, and that another 10% have given up on paying it back, so the bank has "charged off" the loan. Does it seem likely that the data for this hands on came from the larger population of America?

In [60]:
loans %>% group_by(loan_status) %>% summarize(count=n())

ERROR: Error in loans %>% group_by(loan_status) %>% summarize(count = n()): could not find function "%>%"

In [59]:
unique(loans$loan_status)

[1] "Fully Paid"  "Charged Off" "Current"

> loans %>% group_by(loan_status) %>% summarize(count=n())
# A tibble: 3 × 2
  loan_status count
  <chr>       <int>
1 Charged Off  3282
2 Current       502
3 Fully Paid  18173
    
    
    # Ran this in R studio as it was not working in jupyter

In [72]:
loans$status <- NA
loans$status[loans$loan_status == "Charged Off"] <- 1
loans$status[loans$loan_status == "Fully Paid"] <- 0
loans$status[loans$loan_status == "Current"] <- 2

### Run Analysis

In [67]:
observed = c(3282,18173 )

In [68]:
expected = c(0.10, 0.15)

In [73]:
chisq.test(x = observed, p = expected)

ERROR: Error in chisq.test(x = observed, p = expected): probabilities must sum to 1.

Jupyter does not want to work properly or I am doing this completely wrong. I may need to redue this lesson